In [1]:
import torch

In [2]:
from d2l import torch as d2l

In [3]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

In [4]:
X.shape,K.shape

(torch.Size([2, 3, 3]), torch.Size([2, 2, 2]))

In [ ]:
def corr2d_multi_in(X, K):
    # 先遍历“X”和“K”的第0个维度（通道维度），再把它们加在一起
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K))

In [6]:
for x, k in zip(X, K):
    print(x.shape,k.shape)
    print(x)
    break
    

torch.Size([3, 3]) torch.Size([2, 2])
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


In [7]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [11]:
torch.stack([a,b],dim=0)

tensor([[[1., 1.],
         [1., 1.]],

        [[0., 0.],
         [0., 0.]]])

In [12]:
_.shape

torch.Size([2, 2, 2])

In [9]:
torch.stack([a,b],dim=1)

tensor([[[1., 1.],
         [0., 0.]],

        [[1., 1.],
         [0., 0.]]])

In [10]:
_.shape

torch.Size([2, 2, 2])